# Generated by Django 5.2.12 on 2026-04-02 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_alter_user_first_name_alter_user_is_bot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='content_type',
        ),
        migrations.AlterField(
            model_name='message',
            name='chat_id',
            field=models.IntegerField(null=True),
        ),
    ]
